<?php

namespace Database\Seeders;

use App\Models\AnggotaKeluarga;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AnggotaKeluargaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        $anggotaKeluarga = [
            [
                'kk_id' => 1,
                'nik' => '1234567890123456',
                'nama' => 'John Doe',
                'alamat' => '123 Main St',
                'tanggal_lahir' => '1990-01-01',
                'hubungan_keluarga' => 'Ayah',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'Menikah',
            ],
            [
                'kk_id' => 1,
                'nik' => '2345678901234567',
                'nama' => 'Jane Doe',
                'alamat' => '123 Main St',
                'tanggal_lahir' => '1992-05-15',
                'hubungan_keluarga' => 'Ibu',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'B',
                'status_perkawinan' => 'Menikah',
            ],
            [
                'kk_id' => 1,
                'nik' => '3456789012345678',
                'nama' => 'Johny Doe',
                'alamat' => '123 Main St',
                'tanggal_lahir' => '2015-10-10',
                'hubungan_keluarga' => 'Anak',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'O',
                'status_perkawinan' => 'Belum Menikah',
            ],
            [
                'kk_id' => 2,
                'nik' => '4567890123456789',
                'nama' => 'Michael Smith',
                'alamat' => '456 Elm St',
                'tanggal_lahir' => '1988-03-20',
                'hubungan_keluarga' => 'Ayah',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'AB',
                'status_perkawinan' => 'Menikah',
            ],
            [
                'kk_id' => 2,
                'nik' => '5678901234567890',
                'nama' => 'Maria Smith',
                'alamat' => '456 Elm St',
                'tanggal_lahir' => '1990-07-12',
                'hubungan_keluarga' => 'Ibu',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'Menikah',
            ],
            [
                'kk_id' => 2,
                'nik' => '6789012345678901',
                'nama' => 'David Smith',
                'alamat' => '456 Elm St',
                'tanggal_lahir' => '2012-11-25',
                'hubungan_keluarga' => 'Anak',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'B',
                'status_perkawinan' => 'Belum Menikah',
            ],
            [
                'kk_id' => 3,
                'nik' => '7890123456789012',
                'nama' => 'John Brown',
                'alamat' => '789 Oak St',
                'tanggal_lahir' => '1975-12-05',
                'hubungan_keluarga' => 'Ayah',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'O',
                'status_perkawinan' => 'Menikah',
            ],
            [
                'kk_id' => 3,
                'nik' => '8901234567890123',
                'nama' => 'Emily Brown',
                'alamat' => '789 Oak St',
                'tanggal_lahir' => '1978-08-22',
                'hubungan_keluarga' => 'Ibu',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'Menikah',
            ],
            [
                'kk_id' => 3,
                'nik' => '9012345678901234',
                'nama' => 'Jack Brown',
                'alamat' => '789 Oak St',
                'tanggal_lahir' => '2005-03-10',
                'hubungan_keluarga' => 'Anak',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'AB',
                'status_perkawinan' => 'Belum Menikah',
            ],
            [
                'kk_id' => 4,
                'nik' => '0123456789012345',
                'nama' => 'Michael Johnson',
                'alamat' => '321 Pine St',
                'tanggal_lahir' => '1993-11-15',
                'hubungan_keluarga' => 'Ayah',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'B',
                'status_perkawinan' => 'Menikah',
            ],
            [
                'kk_id' => 4,
                'nik' => '1234567890123456',
                'nama' => 'Jessica Johnson',
                'alamat' => '321 Pine St',
                'tanggal_lahir' => '1995-04-25',
                'hubungan_keluarga' => 'Ibu',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'O',
                'status_perkawinan' => 'Menikah',
            ],
            [
                'kk_id' => 4,
                'nik' => '2345678901234567',
                'nama' => 'Sophia Johnson',
                'alamat' => '321 Pine St',
                'tanggal_lahir' => '2018-09-05',
                'hubungan_keluarga' => 'Anak',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'Belum Menikah',
            ],
            [
                'kk_id' => 5,
                'nik' => '3456789012345678',
                'nama' => 'William Wilson',
                'alamat' => '555 Maple St',
                'tanggal_lahir' => '1980-06-30',
                'hubungan_keluarga' => 'Ayah',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'O',
                'status_perkawinan' => 'Menikah',
            ],
            [
                'kk_id' => 5,
                'nik' => '4567890123456789',
                'nama' => 'Olivia Wilson',
                'alamat' => '555 Maple St',
                'tanggal_lahir' => '1982-09-10',
                'hubungan_keluarga' => 'Ibu',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'B',
                'status_perkawinan' => 'Menikah',
            ],
            [
                'kk_id' => 5,
                'nik' => '5678901234567890',
                'nama' => 'Emily Wilson',
                'alamat' => '555 Maple St',
                'tanggal_lahir' => '2006-12-20',
                'hubungan_keluarga' => 'Anak',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'AB',
                'status_perkawinan' => 'Belum Menikah',
            ],
            [
                'kk_id' => 6,
                'nik' => '6789012345678901',
                'nama' => 'James Brown',
                'alamat' => '777 Cedar St',
                'tanggal_lahir' => '1972-08-05',
                'hubungan_keluarga' => 'Ayah',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'Menikah',
            ],
            [
                'kk_id' => 6,
                'nik' => '7890123456789012',
                'nama' => 'Sophia Brown',
                'alamat' => '777 Cedar St',
                'tanggal_lahir' => '1974-03-15',
                'hubungan_keluarga' => 'Ibu',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'O',
                'status_perkawinan' => 'Menikah',
            ],
            [
                'kk_id' => 6,
                'nik' => '8901234567890123',
                'nama' => 'William Brown',
                'alamat' => '777 Cedar St',
                'tanggal_lahir' => '2000-10-25',
                'hubungan_keluarga' => 'Anak',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'B',
                'status_perkawinan' => 'Belum Menikah',
            ],
            [
                'kk_id' => 7,
                'nik' => '9012345678901234',
                'nama' => 'Michael Wilson',
                'alamat' => '888 Oak St',
                'tanggal_lahir' => '1965-05-12',
                'hubungan_keluarga' => 'Ayah',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'A',
                'status_perkawinan' => 'Menikah',
            ],
            [
                'kk_id' => 7,
                'nik' => '0123456789012345',
                'nama' => 'Olivia Wilson',
                'alamat' => '888 Oak St',
                'tanggal_lahir' => '1967-10-18',
                'hubungan_keluarga' => 'Ibu',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'B',
                'status_perkawinan' => 'Menikah',
            ],
            [
                'kk_id' => 7,
                'nik' => '1234567890123456',
                'nama' => 'William Wilson',
                'alamat' => '888 Oak St',
                'tanggal_lahir' => '1995-08-30',
                'hubungan_keluarga' => 'Anak',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'AB',
                'status_perkawinan' => 'Belum Menikah',
            ],
        ];

        
        foreach ($anggotaKeluarga as $anggota) {
            AnggotaKeluarga::create($anggota);
        }
    }
}
